# Generated by Django 3.1.7 on 2021-03-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='ProgrammingKnowledge',
        ),
    ]
